### ISSUE TITLE
The Reading settings are deleted when I set the breakpoint for Responsive Navigation Block

### ISSUE THREAD

**Issue by hagege** [getdave/responsive-navigation-block#5]
The settings on Settings > Reading (Your homepage displays > A static page > Homepage and Posts Page) are lost after  setting the Breakpoint in the settings of your Plugin "Responsive Navigation Block"
![responsive_navigation_block_issue](https://github.com/user-attachments/assets/c999d94c-139d-44fa-94a5-be822fdcaa93)

**Comment by xu4wang** [comment]
same here.

And vise versa, if I set a static page as home page, the break point was deleted(reset to 0).

**Comment by getdave** [comment]
Thanks for the report. I'll take a look at a fix.

**Comment by getdave** [comment]
This should now be fixed and an update has been pushed to WP.org.

I'm sorry that you were effected by this and I appreciate you taking the time to report it.

**Comment by xu4wang** [comment]
thanks for the fix.  works like a charm.

> This should now be fixed and an update has been pushed to WP.org.
> 
> I'm sorry that you were effected by this and I appreciate you taking the time to report it.

**Comment by hagege** [comment]
Great - thanks for fixing the issue.
